@startuml

!includeurl https://raw.githubusercontent.com/rabelenda/cicon-plantuml-sprites/v1.0/sprites/kafka.puml

skinparam class {
    BackgroundColor<<SpringRepository>> LightGreen
    FontColor<<SpringRepository>> Black
    StereotypeFontColor Green
    StereotypeFontSize 15
    StereotypeFontStyle Italic
    BorderColor<<SpringRepository>> DarkGreen
}

rectangle "AuthenticationService" as auth {

    rectangle Infrastructure {

        database RedisAuthenticationStorage as ras {
        }

        database PostgresUserStorage as pus {
        }

        queue "<$kafka>" as kafka {
        }

        package adapter {
            package out {
                package event {
                    class KafkaProducer {
                        + void publishUserCreationEvent(UserCreationEvent event)
                        + void publishLoginEvent(LoginEvent event)
                    }
                }

                package auth {
                       class DefaultAuthenticationProvider {
                           + AuthenticationResponse authenticate(AuthenticationRequest request)
                       }
                }

                package jwt {
                   class JwtTokenProvider {
                       + String generateToken(UserId)
                       + boolean validateToken(String token)
                       + UserId extractUserId(String token)
                   }

                   class JwtRefreshTokenService {
                       + String createToken(UUID userid)
                       + boolean validateToken(String token)
                       + UUID extractUserId(String token)
                       + void invalidateToken(String token)
                   }
                }

                package persistence {
                    class JpaUserAdapter {
                        - JpaUserRepository repository
                        + User save(User user)
                        + Optional<User> findById(UUID id)
                        + Optional<User> findByEmail(String email)
                    }

                    class JpaRoleAdapter {
                        - JpaRoleRepository repository
                        + Role save(Role role)
                        + Optional<Role> getRoleByName(String name)
                    }

                    class RedisRefreshTokenAdapter {
                        - RedisRefreshTokenRepository repository
                        + RefreshToken save(RefreshToken token)
                        + Optional<RefreshToken> getRefreshTokenById(UUID id)
                        + Optional<RefreshToken> getRefreshTokenByUserId(UUID id)
                    }
                }

                package repository {
                    interface JpaUserRepository <<SpringRepository>> {}
                    interface RedisRefreshTokenRepository <<SpringRepository>> {}
                    interface JpaRoleRepository <<SpringRepository>> {}
                }

                JpaUserAdapter o-- JpaUserRepository
                JpaRoleAdapter o-- JpaRoleRepository
                RedisRefreshTokenAdapter o-- RedisRefreshTokenRepository
            }

            package in {
                package web {
                    class AuthenticationController {
                        + ResponseEntity<Void> register(RegisterRequest request)
                        + ResponseEntity<Void> login(LoginRequest request)
                        + ResponseEntity<Void> refresh()
                        + ResponseEntity<Void> logout()
                    }
                }
            }
        }

        JpaRoleRepository --> pus
        JpaUserRepository --> pus
        RedisRefreshTokenRepository --> ras
        KafkaProducer --> kafka
    }

    rectangle Application {
        package annotation {
            interface AuthProvider {
                AuthType value()
            }
        }

        package factory {
            class AuthenticationProviderFactory {
                - Map<AuthType, AuthenticationProvider> providers
                + getProvider(AuthType type)
            }

            note right of AuthenticationProviderFactory
                При инициализации сканирует все AuthenticationProvider,
                извлекает значение @AuthProvider(AuthType)
                и регистрирует в Map<AuthType, AuthenticationProvider>
            end note
        }

        package service {
            class AuthenticationService {
                - AuthenticationProviderFactory providerFactory
                - TokenProvider tokenProvider
                + void authenticate(AuthenticationRequest request)
                + void logout()
                + void refresh()
                + void register(RegisterRequest)
            }
        }

        package model {
            enum AuthType {
                EmailPassword
            }
        }

        package payload {
            package request {
                class RegisterRequest
            }
        }

        AuthenticationService o-- AuthenticationProviderFactory
        AuthenticationService --> RegisterRequest

        AuthenticationProviderFactory --> AuthType
    }

    rectangle Domain {
        package contract {

            package provider {
                interface AuthenticationProvider {
                    + AuthenticationResponse authenticate(AuthenticationRequest request)
                }

                interface TokenProvider {
                    + String generateToken(UserId)
                    + boolean validateToken(String token)
                    + UserId extractUserId(String token)
                }

                note bottom of AuthenticationProvider
                    Это sealed интерфейс
                end note
            }

            package repository {
                interface UserRepository {
                    + User save(User user)
                    + Optional<User> findById(UUID id)
                    + Optional<User> findByEmail(String email)
                }

                interface RoleRepository {
                    + Role save(Role role)
                    + Optional<Role> getRoleByName(String name)
                }

                interface RefreshTokenRepository {
                    + RefreshToken save(RefreshToken token)
                    + Optional<RefreshToken> getRefreshTokenById(UUID id)
                    + Optional<RefreshToken> getRefreshTokenByUserId(UUID id)
                }
            }

            package service {
                interface RefreshTokenService {
                    + String createToken(UUID userid)
                    + boolean validateToken(String token)
                    + UUID extractUserId(String token)
                    + void invalidateToken(String token)
                }

                interface EventPublisher {
                    + void publishUserCreationEvent(UserCreationEvent event)
                    + void publishLoginEvent(LoginEvent event)
                }
            }
        }

        package payload {
            package request {
                class AuthenticationRequest
            }
        }

        package model {
            class Role
            class User
            class RefreshToken
        }

        AuthenticationProvider --> AuthenticationRequest
        UserRepository --> User
        RoleRepository --> Role
        RefreshTokenRepository --> RefreshToken
    }

    JwtTokenProvider ..|> TokenProvider
    DefaultAuthenticationProvider ..|> JpaUserAdapter
    JpaUserAdapter ..|> UserRepository
    RedisRefreshTokenAdapter ..|> RefreshTokenRepository
    JpaRoleAdapter ..|> RoleRepository
    KafkaProducer ..|> EventPublisher
    JwtRefreshTokenService ..|> RefreshTokenService

    AuthenticationProviderFactory o-- AuthenticationProvider

    AuthenticationController o-- AuthenticationService

    AuthenticationService --> AuthenticationRequest
    AuthenticationService o-- TokenProvider
    AuthenticationService o-- RoleRepository

    DefaultAuthenticationProvider o-- JpaUserAdapter
    DefaultAuthenticationProvider ..> AuthProvider

    JwtRefreshTokenService o-- RedisRefreshTokenAdapter

    RegisterRequest --> Role
}

@enduml